keys:
  - &kaladin age1a4gafggwkfhfxxl246gc9leyr645z22hhlfew5z50tgwcn9edewq0tcn85
  - &primary age19p7uhtn9d5eqszn0t8ff2f6n8nuzkx32wzylsvjmhq9gpwjy5p9qenr3sj
  - &ohnezahn age17x4dh9q0ucp698sgvl7npx478js0uw05kte4pffrn6cmfxdsf94q4vlkse
creation_rules:
  - path_regex: hosts/kaladin/secrets.yaml$
    key_groups:
    - age:
      - *kaladin
      - *primary
      - *ohnezahn
